name: firestore
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  firebase_admin_interop: ^2.1.0
  meta: ^1.3.0
  node_interop: <=1.2.1
  node_io: ^1.2.0
  yaml: ^2.1.2

dependency_overrides: 
  build_node_compilers: 
    git: 
      url: https://github.com/pulyaevskiy/node-interop.git
      path: build_node_compilers
  #node_io:
  #  git: 
  #    url: https://github.com/pulyaevskiy/node-interop.git
  #    path: node_io
  #node_interop: 
  #  git: 
  #    url: https://github.com/pulyaevskiy/node-interop.git
  #    path: node_interop
  #  version: <=1.2.1


dev_dependencies:
  build_node_compilers: ^0.3.2
  build_runner: ^1.0.0

#  test: ^1.6.0
